site_name: IBM Passkey Extension Docs
repo_url: https://github.com/lachlan-ibm/ibm-security-passkey-extension
nav:
- Home:
    - index.md
    - Quickstart: quickstart.md
    - Developer: developers.md

theme:
  name: material
  logo: ibm-cloud--hyper-protect-crypto-services-96x96.png
  features:
  features:
  - announce.dismiss
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.path
  - search.highlight
  - search.suggest
  - toc.follow
  - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: lime
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list